[paths]
pkg = "pkg"
unpacked = "unpacked"
output = "output"
work = "work"

[extract]
jobs = 2
resume = true

[merge]
apply_all_patches = true

[shadowmount]
compatibility = "current-smp"
dlc_mode = "off"

[pack]
format = "ffpfsc"
inner_filesystem = "exfat"
verify = true
keep_inner_image = false
compression_level = 7
